### ISSUE TITLE
Without script_compatibility [Question]

### ISSUE THREAD

**Issue by Yousha** [Lordzy/safeDialogs#1]
Can we use this script without including <script_compatibility> ?
I mean comment/remove it.

**Comment by Lordzy** [comment]
Hi,
Yes, but you'll have to add support for both filterscript and gamemode by your own then. The reason why I used script_compatibility is to provide support for both modes with ease. I can work on a standalone version if you want.

If you're using this include, please consider using v1.0.2 of this include which has some major fix.

EDIT : v1.0.2 no longer uses script_compatibility since it creates collision for users using YSI. Also, false triggers for dialogs using color embedding have been fixed.

**Comment by Yousha** [comment]
Yea sure, that old version gives many false reports(reported me too many times)
Thanks.

**Comment by Lordzy** [comment]
Let me know if there are any issues, thanks.
