### ISSUE TITLE
Problem with fixes.inc (?)

### ISSUE THREAD

**Issue by ehylla93** [Lordzy/safeDialogs#2]
```
#include <a_samp>
#include <fixes>
#include <safeDialogs>

D:\Program Files (x86)\Pawno\include\safeDialogs.inc(129) : error 017: undefined symbol "_ALS"
D:\Program Files (x86)\Pawno\include\safeDialogs.inc(129) : error 029: invalid expression, assumed zero
D:\Program Files (x86)\Pawno\include\safeDialogs.inc(129) : error 017: undefined symbol "_ALS_go"
D:\Program Files (x86)\Pawno\include\safeDialogs.inc(129) : fatal error 107: too many error messages on one line

Compilation aborted.

Pawn compiler 3.10.1	 	 	Copyright (c) 1997-2006, ITB CompuPhase


4 Errors.
```

and / or

```
#include <a_samp>
#include <safeDialogs>
#include <fixes>

D:\Program Files (x86)\Pawno\include\fixes.inc(3500) : fatal error 111: user error: _ALS_OnFilterScriptInit defined


Compilation aborted.

Pawn compiler 3.10.1	 	 	Copyright (c) 1997-2006, ITB CompuPhase


1 Error.
```

Maybe it's a problem with fixes.inc, but can it be fixed in your include?

**Comment by Lordzy** [comment]
Hi,
Thank you for reporting. It seems to be caused due to my include attempting to call OnPlayerConnect callback directly upon initialization. Please consider downloading the latest commit of this include, it has been fixed to be compatible with other libraries hooking callbacks.

The problem was caused by fixes.inc - It should've worked fine on your second attempt (including safeDialogs before fixes.inc) but fixes.inc will pop out user error in case if any of the callbacks mentioned in fixes.inc is defined already. The purpose of fixes.inc was to be included first before any other codes. fixes.inc does not deal much with dialog related stuffs, so you can include safeDialogs after fixes.inc.

**Comment by ehylla93** [comment]
It works fine now. But yeah, it has to be included after fixed.inc.
